model:
  arch: minigpt4
  model_type: pretrain_llama2

  max_txt_len: 256
  end_sym: "</s>"
  prompt_path: "prompts/imad_mix_special_toks.txt"
  prompt_path_cmd: "prompts/imad_mix_cmd_special_toks.txt" # Prompts by having given command
  prompt_template: '[INST] {} [/INST] '
  ckpt: 'stage_2_checkpoint/pretrained_minigpt4_llama2_7b.pth' # This is stage-2 minigpt4 checkpoint

datasets:
  IMAD:
    batch_size: 2
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: image_text_pretrain
#   # optimizer
#   lr_sched: "linear_warmup_cosine_lr"
#   init_lr: 3e-5
#   min_lr: 1e-5
#   # init_lr: 1e-5
#   # min_lr: 1e-6
#   warmup_lr: 1e-6

#   weight_decay: 0.05
#   max_epoch: 5
#   iters_per_epoch: 200
#   num_workers: 4
#   warmup_steps: 200

  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-4
  min_lr: 8e-5
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 10
  num_workers: 4
  warmup_steps: 5000
  # iters_per_epoch: 5000

  seed: 42
  output_dir: "output/minigpt4_stage2_finetune"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]
  valid_splits: ["valid"]
  test_splits: ["test"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: True
  job_name: MiniGPT-Reverse-Designing